apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: photo-wall
  version: 1.0.0
spec:
  enabled: true
  requires: ">=2.0.0"
  author:
    name: YourName
  displayName: "照片视频墙"
  description: "为Halo博客添加支持图片+视频+分类标签的照片墙功能，支持MOV格式视频自动播放"
  logo: https://yourwebsite.com/logo.png
  homepage: https://github.com/yourname/photo-wall-plugin
  license:
    - name: "MIT"
      url: "https://opensource.org/licenses/MIT"
  menu:
    - id: photo-wall-admin
      name: 照片视频墙管理
      icon: fa-solid fa-images
      path: /admin/photo-wall
      parent: dashboard
      priority: 100
